networks:
  lorawisep_fastapi_network:
    driver: bridge

services:
  # Serviço para a aplicação FastAPI
  web:
    build: .
    container_name: lorawisep_fastapi_app
    volumes:
      - .:/app
      # - /home/pedro/Documentos/ns-3-dev/:/ns3
      - /home/wisep/ns-3-allinone/ns-3.43:/ns3
    ports:
      - "8888:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - lorawisep_fastapi_network
    stdin_open: true
    tty: true

  # Serviço para o banco de dados PostgreSQL
  db:
    image: postgres:latest
    container_name: postgres_db_lorawisep
    environment:
      POSTGRES_USER: lorawisep_fastapi_user
      POSTGRES_PASSWORD: lorawisep_password123
      POSTGRES_DB: lorawisep_fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lorawisep_fastapi_network

volumes:
  postgres_data:

